# ---- Etapa de Build ----
FROM golang:1.24.0 AS builder

WORKDIR /app

# Copia toda a pasta `test` e a pasta `server/src`
COPY test/ ./test
COPY server/src/ ./server/src

# Define o diretório onde está o go.mod e o main.go
WORKDIR /app/test/cmd

# Baixa as dependências
RUN go mod download

# Cria a pasta bin e compila o binário
RUN mkdir -p /app/bin
RUN go build -o /app/bin/test .

# ---- Etapa Final ----
FROM debian:bookworm-slim

WORKDIR /app

# Copia o binário gerado
COPY --from=builder /app/bin/test .

# Garante permissão de execução
RUN chmod +x ./test

# Comando de inicialização
CMD ["./test"]
